# BASE UI
ColorColumn: "backgroundDark"
Conceal: ""
Cursor: "contrast"
CursorIM: ""
CursorColumn: ""
CursorLine: ""
Directory: ""
DiffAdd: ""
DiffChange: ""
DiffDelete: ""
DiffText: ""
ErrorMsg: "invalid"
VertSplit: ""
Folded: ""
FoldColumn: ""
SignColumn: ""
IncSearch: "backgroundDark searchHighlight"
LineNr: "foreground gutter"
CursorLineNr: "white gutter"
MatchParen: "background contrast"
ModeMsg: ""
MoreMsg: ""
NonText: ""
Normal: "white background"
PMenu: "foreground menuBackground"
PMenuSel: "other background"
PmenuSbar: ""
PmenuThumb: ""
Question: ""
Search: "backgroundDark currentSearch"
SpecialKey: ""
SpellBad: ""
SpellLocal: ""
SpellCap: ""
SpellRare: ""
StatusLine: "- backgroundDark"
StatusLineNC: ""
TabLine: ""
TabLineFill: ""
TabLineSel: ""
Title: ""
Visual: "- selectionBackground"
VisualNOS: ""
WarningMsg: "contrast"
WildMenu: "- backgroundDark"
# BASE SYNTAX
Comment: "comment"
Constant: "constants"
String: "strings" # Constant
Character: "" # Constant
Boolean: "" # Constant
Number: "" # Constant
Float: "" # Constant
Identifier: "keywords"
Function: "keywords" # Identifier
Statement: ""
Conditional: "keywords" # Statement
Repeat: "" # Statement
Label: "" # Statement
Operator: "keywords ." # Statement
Keyword: "" # Statement
Exception: "" # Statement
PreProc: ""
Include: "" # PreProc
Define: "" # PreProc
Macro: "" # PreProc
PreCondit: "" # PreProc
Type: "objectKeys ."
StorageClass: "keywords ." # Type
Structure: "contrastLite" # Type
Typedef: "" # Type
Special: ""
SpecialChar: "" # Special
Tag: "" # Special
Delimiter: "" # Special
SpecialComment: "" # Special
Debug: "" # Special
Underlined: "invalid"
Ignore: ""
Error: "invalid"
Todo: "highlight"
